# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifying JVM arguments for the Gradle Daemon
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
# When configured, Gradle will run in parallel of the same project
org.gradle.parallel=true
# AndroidX libraries use the namespace instead of the package name
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true
