package com.quangthe.amlich

import java.util.Calendar

object QuoteService {

    data class DailyQuote(
        val content: String,
        val author: String
    )

    private val BUDDHIST_QUOTES = listOf(
        DailyQuote("Hạnh phúc không phải là có tất cả những gì bạn muốn, mà là trân trọng những gì bạn đang có.", "Lời Phật Dạy"),
        DailyQuote("Đừng bám víu vào quá khứ, đừng mơ mộng về tương lai, hãy tập trung tâm trí vào khoảnh khắc hiện tại.", "Đức Phật"),
        DailyQuote("Hận thù không bao giờ dập tắt được hận thù, chỉ có tình yêu thương mới dập tắt được hận thù.", "Kinh Pháp Cú"),
        DailyQuote("Mỗi buổi sáng chúng ta lại được tái sinh. Những gì chúng ta làm hôm nay là quan trọng nhất.", "Đức Phật"),
        DailyQuote("Nếu bạn tìm thấy một người bạn đồng hành khôn ngoan và đức hạnh, hãy đi cùng họ, vượt qua mọi nguy hiểm, vui vẻ và tỉnh thức.", "Kinh Pháp Cú"),
        DailyQuote("Tâm là cội nguồn của mọi việc. Nếu tâm thanh tịnh, hạnh phúc sẽ theo ta như hình với bóng.", "Kinh Pháp Cú"),
        DailyQuote("Không có gì quý giá hơn là được sống trong tỉnh thức.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy là hòn đảo cho chính mình, hãy là nơi nương tựa cho chính mình.", "Đức Phật"),
        DailyQuote("Bình yên đến từ bên trong. Đừng tìm kiếm nó bên ngoài.", "Đức Phật"),
        DailyQuote("Sức khỏe là món quà lớn nhất, sự hài lòng là của cải lớn nhất, sự chung thủy là mối quan hệ tốt nhất.", "Đức Phật"),
        DailyQuote("Khi ta thay đổi, thế giới quanh ta cũng thay đổi.", "Lời Phật Dạy"),
        DailyQuote("Đừng nói trừ khi lời nói đó làm đẹp thêm sự im lặng.", "Lời Phật Dạy"),
        DailyQuote("Một ngọn nến có thể thắp sáng hàng ngàn ngọn nến khác, và cuộc đời của nó không bị ngắn lại. Hạnh phúc không bao giờ giảm đi khi được chia sẻ.", "Đức Phật"),
        DailyQuote("Bạn chỉ mất những gì bạn bám giữ.", "Đức Phật"),
        DailyQuote("Cơn giận là một hình phạt mà ta tự dành cho mình vì lỗi lầm của người khác.", "Lời Phật Dạy"),
        DailyQuote("Lòng từ bi và lòng nhân ái là nền tảng của mọi tôn giáo.", "Đức Phật"),
        DailyQuote("Sống một ngày tỉnh thức còn hơn sống một trăm năm mê muội.", "Kinh Pháp Cú"),
        DailyQuote("Hãy thắp đuốc lên mà đi, hãy lấy pháp của ta làm đuốc.", "Đức Phật"),
        DailyQuote("Vạn pháp duy tâm tạo.", "Kinh Hoa Nghiêm"),
        DailyQuote("Buông bỏ là cách tốt nhất để đạt được sự bình yên.", "Lời Phật Dạy"),
        DailyQuote("Mỗi bước chân đi trên mặt đất là một phép lạ.", "Thích Nhất Hạnh"),
        DailyQuote("Tình thương là ánh sáng xua tan bóng tối của sự ích kỷ.", "Lời Phật Dạy"),
        DailyQuote("Người chiến thắng chính mình còn vẻ vang hơn chiến thắng vạn quân trên chiến trường.", "Kinh Pháp Cú"),
        DailyQuote("Cuộc đời là một dòng sông, hãy để nó trôi chảy tự nhiên.", "Lời Phật Dạy"),
        DailyQuote("Hãy mỉm cười với hơi thở vào, và mỉm cười với hơi thở ra.", "Thích Nhất Hạnh"),
        DailyQuote("Sự thật mang lại sự tự do.", "Đức Phật"),
        DailyQuote("Khi tâm yên tĩnh, cả thế giới sẽ yên tĩnh theo.", "Lời Phật Dạy"),
        DailyQuote("Đừng tìm kiếm hạnh phúc ở nơi xa xôi, nó nằm ngay trong tâm ta.", "Lời Phật Dạy"),
        DailyQuote("Lòng biết ơn là chìa khóa của sự đủ đầy.", "Lời Phật Dạy"),
        DailyQuote("Hãy sống như một đóa hoa sen, gần bùn mà chẳng hôi tanh mùi bùn.", "Lời Phật Dạy"),
        DailyQuote("Kiên nhẫn là đức hạnh cao quý nhất.", "Đức Phật"),
        DailyQuote("Không có con đường nào dẫn đến hạnh phúc, hạnh phúc chính là con đường.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy đối xử với người khác như cách bạn muốn họ đối xử với mình.", "Lời Phật Dạy"),
        DailyQuote("Sự khiêm tốn là dấu hiệu của người trí tuệ.", "Lời Phật Dạy"),
        DailyQuote("Hành động tốt là hạt giống cho tương lai tươi sáng.", "Lời Phật Dạy"),
        DailyQuote("Bình tĩnh trước biến động là sức mạnh của tâm hồn.", "Lời Phật Dạy"),
        DailyQuote("Mỗi người là kiến trúc sư cho vận mệnh của chính mình.", "Đức Phật"),
        DailyQuote("Tình yêu không có sự hiểu biết thì không phải là tình yêu chân thực.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy học cách lắng nghe để hiểu sâu sắc hơn.", "Thích Nhất Hạnh"),
        DailyQuote("Sự im lặng là câu trả lời tốt nhất cho những lời xúc phạm.", "Lời Phật Dạy"),
        DailyQuote("Đừng làm tổn thương người khác bằng những lời nói sắc nhọn.", "Lời Phật Dạy"),
        DailyQuote("Lòng nhân từ là ngôn ngữ mà người điếc có thể nghe và người mù có thể thấy.", "Lời Phật Dạy"),
        DailyQuote("Hạnh phúc là khi suy nghĩ, lời nói và hành động thống nhất với nhau.", "Lời Phật Dạy"),
        DailyQuote("Hãy trân trọng những gì bạn có trước khi thời gian khiến bạn trân trọng những gì bạn từng có.", "Lời Phật Dạy"),
        DailyQuote("Sống đơn giản cho đời thanh thản.", "Lời Phật Dạy"),
        DailyQuote("Sự chấp ngã là nguồn gốc của mọi khổ đau.", "Đức Phật"),
        DailyQuote("Trí tuệ bắt đầu từ sự tự nhận thức.", "Lời Phật Dạy"),
        DailyQuote("Hãy luôn giữ tâm thái lạc quan dù trong hoàn cảnh khó khăn nhất.", "Lời Phật Dạy"),
        DailyQuote("Lòng khoan dung là liều thuốc cho tâm hồn.", "Lời Phật Dạy"),
        DailyQuote("Mỗi ngày là một cơ hội mới để yêu thương và sẻ chia.", "Lời Phật Dạy"),
        DailyQuote("Đừng để tâm trí bị cuốn theo những muộn phiền không đáng có.", "Lời Phật Dạy"),
        DailyQuote("Hãy trân trọng từng phút giây hiện tại, đó là món quà vô giá.", "Thích Nhất Hạnh"),
        DailyQuote("Tâm không vướng bận, đời tự tại an nhiên.", "Lời Phật Dạy"),
        DailyQuote("Mọi sự khổ đau đều bắt nguồn từ lòng tham và sự ích kỷ.", "Đức Phật"),
        DailyQuote("Hãy nhìn thế giới bằng đôi mắt của lòng từ bi.", "Đức Phật"),
        DailyQuote("Sự thật là ánh sáng xua tan bóng tối của sự vô minh.", "Lời Phật Dạy"),
        DailyQuote("Hãy là người mang lại niềm vui cho mọi người xung quanh.", "Lời Phật Dạy"),
        DailyQuote("Lòng nhân hậu là sức mạnh lớn nhất của con người.", "Lời Phật Dạy"),
        DailyQuote("Bình yên không phải là không có sóng gió, mà là sự tĩnh lặng trong tâm hồn giữa bão tố.", "Lời Phật Dạy"),
        DailyQuote("Hãy học cách buông bỏ những gì không còn phục vụ cho sự phát triển của bạn.", "Lời Phật Dạy"),
        DailyQuote("Trái tim yêu thương là khởi đầu của mọi trí tuệ.", "Lời Phật Dạy"),
        DailyQuote("Sống tỉnh thức là sống trọn vẹn từng khoảnh khắc.", "Thích Nhất Hạnh"),
        DailyQuote("Mỗi khó khăn là một bài học giúp ta trưởng thành hơn.", "Lời Phật Dạy"),
        DailyQuote("Hãy luôn mỉm cười, vì cuộc đời vẫn rất tươi đẹp.", "Lời Phật Dạy"),
        DailyQuote("Sự tha thứ mang lại sự bình yên cho chính người tha thứ.", "Lời Phật Dạy"),
        DailyQuote("Đừng so sánh mình với người khác, hãy vượt qua chính mình của ngày hôm qua.", "Lời Phật Dạy"),
        DailyQuote("Tâm hồn trong sạch là nơi trú ngụ của hạnh phúc.", "Lời Phật Dạy"),
        DailyQuote("Hãy biết ơn cả những điều nhỏ nhặt nhất trong cuộc sống.", "Lời Phật Dạy"),
        DailyQuote("Tình thương không biên giới là con đường dẫn đến giác ngộ.", "Đức Phật"),
        DailyQuote("Hãy lắng nghe tiếng nói của trái tim mình.", "Lời Phật Dạy"),
        DailyQuote("Sự kiên trì sẽ dẫn lối đến thành công.", "Lời Phật Dạy"),
        DailyQuote("Đừng bao giờ từ bỏ hy vọng, ánh sáng luôn ở phía trước.", "Lời Phật Dạy"),
        DailyQuote("Hãy sống một cuộc đời có ý nghĩa và giá trị.", "Lời Phật Dạy"),
        DailyQuote("Mỗi hành động tử tế đều để lại dấu ấn tốt đẹp.", "Lời Phật Dạy"),
        DailyQuote("Hãy tìm thấy niềm vui trong sự đơn giản.", "Lời Phật Dạy"),
        DailyQuote("Tâm trí tĩnh lặng là nguồn gốc của sự sáng tạo.", "Lời Phật Dạy"),
        DailyQuote("Hãy chia sẻ những gì bạn có, dù là một nụ cười hay một lời an ủi.", "Lời Phật Dạy"),
        DailyQuote("Cuộc đời là một chuyến hành trình, hãy tận hưởng từng bước đi.", "Lời Phật Dạy"),
        DailyQuote("Hạnh phúc thực sự nằm ở sự cho đi.", "Lời Phật Dạy"),
        DailyQuote("Hãy giữ cho tâm hồn luôn rộng mở và bao dung.", "Lời Phật Dạy"),
        DailyQuote("Sự hiểu biết mang lại sự cảm thông sâu sắc.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy sống chân thành và trung thực với chính mình.", "Lời Phật Dạy"),
        DailyQuote("Mọi thay đổi đều bắt đầu từ chính bản thân ta.", "Lời Phật Dạy"),
        DailyQuote("Hãy trân trọng những mối nhân duyên trong đời.", "Lời Phật Dạy"),
        DailyQuote("Bình yên là khi tâm ta không còn sóng gió.", "Lời Phật Dạy"),
        DailyQuote("Hãy luôn tin vào những điều tốt đẹp.", "Lời Phật Dạy"),
        DailyQuote("Sự bao dung là vẻ đẹp của tâm hồn.", "Lời Phật Dạy"),
        DailyQuote("Hãy sống như một dòng nước, mềm mại nhưng mạnh mẽ.", "Lời Phật Dạy"),
        DailyQuote("Mỗi ngày hãy dành thời gian để tĩnh tâm và suy ngẫm.", "Lời Phật Dạy"),
        DailyQuote("Những ý nghĩ tốt đẹp tạo ra những hành động tốt đẹp.", "Kinh Pháp Cú"),
        DailyQuote("Không ai cứu được ai ngoài chính bản thân mình.", "Đức Phật"),
        DailyQuote("Niềm vui lớn nhất trong đời là được làm điều tốt cho người khác.", "Lời Phật Dạy"),
        DailyQuote("Sự khổ đau là một phần của cuộc sống, nhưng không phải là tất cả.", "Đức Phật"),
        DailyQuote("Hãy yêu thương vô điều kiện, đó là bản chất của tình yêu chân thật.", "Đức Phật"),
        DailyQuote("Mỗi suy nghĩ của bạn là một lời nguyện, mỗi hành động là một lời cầu.", "Thích Nhất Hạnh"),
        DailyQuote("Trong tâm ta có Phật, Phật ở tại tâm.", "Kinh Hoa Nghiêm"),
        DailyQuote("Sống cho nhau là sống đẹp nhất.", "Lời Phật Dạy"),
        DailyQuote("Hãy nhẹ nhàng với chính mình và với người khác.", "Thích Nhất Hạnh"),
        DailyQuote("Đừng cưỡng lại dòng chảy của cuộc đời, hãy hòa nhập với nó.", "Lời Phật Dạy"),
        DailyQuote("Sự rộng lượng là cửa ngõ dẫn đến hạnh phúc.", "Kinh Pháp Cú"),
        DailyQuote("Hãy sống như một vì sao, tỏa sáng trong bóng tối.", "Lời Phật Dạy"),
        DailyQuote("Tình yêu thương là sợi dây kết nối muôn loài.", "Đức Phật"),
        DailyQuote("Chớ có hờn giận, chớ có oán thù, đó là con đường dẫn đến bình an.", "Kinh Pháp Cú"),
        DailyQuote("Mọi thứ đều vô thường, hãy trân trọng từng khoảnh khắc.", "Đức Phật"),
        DailyQuote("Từ bi là nguồn nước mát cho tâm hồn khô hạn.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy học cách buông bỏ, vì càng bám víu càng khổ đau.", "Lời Phật Dạy"),
        DailyQuote("Cuộc sống là một món quà, hãy nâng niu nó.", "Đức Phật"),
        DailyQuote("Không có kẻ thù nào nguy hiểm bằng sự ngu dốt của chính mình.", "Kinh Pháp Cú"),
        DailyQuote("Hãy sống với lương tâm trong sáng, đó là điều quý giá nhất.", "Lời Phật Dạy"),
        DailyQuote("Sự tĩnh lặng là ngôn ngữ của trí tuệ.", "Thích Nhất Hạnh"),
        DailyQuote("Mỗi người đều mang trong mình hạt giống của sự giác ngộ.", "Đức Phật"),
        DailyQuote("Đừng để lòng tham làm mờ mắt, hãy sống với sự vừa đủ.", "Lời Phật Dạy"),
        DailyQuote("Hạnh phúc đích thực là khi ta biết đủ.", "Lời Phật Dạy"),
        DailyQuote("Lời nói chân thật là ngọn đèn soi sáng tâm hồn.", "Kinh Pháp Cú"),
        DailyQuote("Hãy đối diện với khó khăn bằng lòng dũng cảm và trí tuệ.", "Đức Phật"),
        DailyQuote("Đời người ngắn ngủi, đừng lãng phí vào những điều vô bổ.", "Lời Phật Dạy"),
        DailyQuote("Sự tỉnh thức là ánh sáng trong tâm hồn.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy tha thứ cho người khác, đó là cách giải thoát cho chính mình.", "Lời Phật Dạy"),
        DailyQuote("Tâm bình thế giới bình.", "Kinh Hoa Nghiêm"),
        DailyQuote("Hãy luôn giữ một trái tim ấm áp và một tâm hồn cởi mở.", "Lời Phật Dạy"),
        DailyQuote("Không có con đường nào dễ dàng, nhưng mọi con đường đều dẫn đến sự trưởng thành.", "Đức Phật"),
        DailyQuote("Mỗi ngày hãy làm một việc tốt, dù nhỏ.", "Lời Phật Dạy"),
        DailyQuote("Sự kiêu ngạo là bức tường ngăn cách ta với hạnh phúc.", "Kinh Pháp Cú"),
        DailyQuote("Hãy sống khiêm tốn, vì tất cả đều vô thường.", "Đức Phật"),
        DailyQuote("Tình thương là sức mạnh lớn nhất trên thế gian.", "Lời Phật Dạy"),
        DailyQuote("Đừng đánh giá người khác qua vẻ bề ngoài, hãy nhìn vào tâm họ.", "Lời Phật Dạy"),
        DailyQuote("Sự bình an trong tâm là món quà vô giá.", "Đức Phật"),
        DailyQuote("Hãy biết ơn những ai đã giúp đỡ bạn trên đường đời.", "Lời Phật Dạy"),
        DailyQuote("Mọi sự đều có nhân duyên của nó.", "Lời Phật Dạy"),
        DailyQuote("Hãy sống đẹp, nghĩ đẹp và làm đẹp.", "Lời Phật Dạy"),
        DailyQuote("Sự chân thành là nền tảng của mọi mối quan hệ.", "Đức Phật"),
        DailyQuote("Đừng để quá khứ ám ảnh và tương lai làm bạn lo âu.", "Thích Nhất Hạnh"),
        DailyQuote("Lòng từ bi là ngọn lửa sưởi ấm trái tim.", "Lời Phật Dạy"),
        DailyQuote("Hãy trân trọng những gì đang có, vì tất cả đều đến rồi đi.", "Lời Phật Dạy"),
        DailyQuote("Mỗi thử thách là một cơ hội để vươn lên.", "Đức Phật"),
        DailyQuote("Sống tỉnh thức là sống có ý thức về từng giây phút.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy nuôi dưỡng tâm hồn bằng những suy nghĩ tích cực.", "Lời Phật Dạy"),
        DailyQuote("Đừng tìm cầu sự hoàn hảo bên ngoài, hãy hoàn thiện chính mình.", "Lời Phật Dạy"),
        DailyQuote("Tình thương chân thật không có điều kiện.", "Đức Phật"),
        DailyQuote("Sự đau khổ sẽ qua đi, như bài học còn ở lại.", "Lời Phật Dạy"),
        DailyQuote("Hãy là một người mang lại bình an cho người khác.", "Thích Nhất Hạnh"),
        DailyQuote("Mỗi việc làm tốt đều gieo một hạt giống lành.", "Kinh Pháp Cú"),
        DailyQuote("Đừng để vật chất làm chủ, hãy làm chủ vật chất.", "Lời Phật Dạy"),
        DailyQuote("Sự giận dữ thiêu đốt tâm hồn, hãy học cách kiểm soát nó.", "Đức Phật"),
        DailyQuote("Hãy sống với tất cả lòng biết ơn và yêu thương.", "Lời Phật Dạy"),
        DailyQuote("Thiền định là con đường dẫn đến sự tĩnh lặng sâu sắc.", "Thích Nhất Hạnh"),
        DailyQuote("Đừng sợ thất bại, đó là bài học quý giá trên đường đời.", "Đức Phật"),
        DailyQuote("Hãy đặt niềm tin vào chính mình, đó là sức mạnh to lớn.", "Lời Phật Dạy"),
        DailyQuote("Mọi oán thù đều có thể hóa giải bằng tình yêu thương.", "Kinh Pháp Cú"),
        DailyQuote("Hãy sống trọn vẹn với hiện tại, đó là bí quyết của hạnh phúc.", "Lời Phật Dạy"),
        DailyQuote("Sự im lặng đôi khi nói lên nhiều hơn ngàn lời.", "Lời Phật Dạy"),
        DailyQuote("Lòng trắc ẩn là phẩm chất cao đẹp nhất của con người.", "Đức Phật"),
        DailyQuote("Hãy buông bỏ những lo âu không cần thiết.", "Thích Nhất Hạnh"),
        DailyQuote("Mỗi người đều có Phật tính, hãy đánh thức nó.", "Kinh Pháp Hoa"),
        DailyQuote("Cuộc đời là vô thường, hãy sống thật ý nghĩa.", "Lời Phật Dạy"),
        DailyQuote("Lòng tham là đám mây đen che phủ ánh sáng tâm hồn.", "Kinh Pháp Cú"),
        DailyQuote("Sống lành mạnh về thân, lời nói và ý nghĩ.", "Lời Phật Dạy"),
        DailyQuote("Hãy cho đi mà không mong cầu nhận lại.", "Đức Phật"),
        DailyQuote("Sự tập trung là chìa khóa của thành công.", "Lời Phật Dạy"),
        DailyQuote("Đừng để tâm bị xao động bởi những điều nhỏ nhặt.", "Lời Phật Dạy"),
        DailyQuote("Hạnh phúc không mua được bằng tiền, mà bằng tình yêu thương.", "Lời Phật Dạy"),
        DailyQuote("Hãy là ánh sáng cho chính mình.", "Đức Phật"),
        DailyQuote("Sống chậm lại, cảm nhận sâu hơn, yêu thương nhiều hơn.", "Thích Nhất Hạnh"),
        DailyQuote("Đừng phán xét, hãy thấu hiểu.", "Đức Phật"),
        DailyQuote("Mỗi ngày là một trang giấy trắng, hãy viết nên những điều tốt đẹp.", "Lời Phật Dạy"),
        DailyQuote("Sự nhẫn nại là sức mạnh của người trí.", "Lời Phật Dạy"),
        DailyQuote("Hãy tìm thấy niềm vui trong công việc hàng ngày.", "Lời Phật Dạy"),
        DailyQuote("Đời sống là sự kết nối, hãy sống hòa hợp với muôn loài.", "Đức Phật"),
        DailyQuote("Cái chết không phải là kết thúc, mà là sự chuyển hóa.", "Lời Phật Dạy"),
        DailyQuote("Hãy sống với tâm hồn thanh thản và nhẹ nhàng.", "Lời Phật Dạy"),
        DailyQuote("Tình yêu thương không biên giới là con đường dẫn đến giải thoát.", "Đức Phật"),
        DailyQuote("Sự nóng giận là ngọn lửa thiêu rụi công đức.", "Kinh Pháp Cú"),
        DailyQuote("Hãy là người bạn tốt của chính mình trước đã.", "Thích Nhất Hạnh"),
        DailyQuote("Mọi khổ đau đều có nguyên nhân, hãy tìm hiểu để vượt qua.", "Đức Phật"),
        DailyQuote("Sống có trách nhiệm với bản thân và với cộng đồng.", "Lời Phật Dạy"),
        DailyQuote("Đừng tranh cãi hơn thua, đó là nguồn gốc của xung đột.", "Lời Phật Dạy"),
        DailyQuote("Hãy nuôi dưỡng tình yêu thương từ những điều nhỏ nhất.", "Thích Nhất Hạnh"),
        DailyQuote("Sự thanh tịnh của tâm là nơi trú ẩn an toàn nhất.", "Đức Phật"),
        DailyQuote("Mỗi suy nghĩ tích cực là một bước đến gần hạnh phúc.", "Lời Phật Dạy"),
        DailyQuote("Hãy sống với đạo đức và lương tâm trong sáng.", "Lời Phật Dạy"),
        DailyQuote("Đừng vội vàng kết luận, hãy nhìn nhận mọi việc một cách khách quan.", "Lời Phật Dạy"),
        DailyQuote("Tình thương là chất keo gắn kết các mối quan hệ.", "Đức Phật"),
        DailyQuote("Sự hy sinh cao quý nhất là hy sinh lòng ích kỷ.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy biết đủ, đó là của cải lớn nhất.", "Kinh Pháp Cú"),
        DailyQuote("Cuộc đời là một bức tranh, hãy tô màu bằng tình yêu thương.", "Lời Phật Dạy"),
        DailyQuote("Không ai có thể làm tổn thương bạn nếu bạn không cho phép.", "Đức Phật"),
        DailyQuote("Hãy thực hành chánh niệm trong mọi việc.", "Thích Nhất Hạnh"),
        DailyQuote("Sự trung thực là nền tảng của đạo đức.", "Lời Phật Dạy"),
        DailyQuote("Mỗi hơi thở là một món quà, hãy trân trọng nó.", "Lời Phật Dạy"),
        DailyQuote("Đừng mong cầu người khác thay đổi, hãy thay đổi chính mình.", "Lời Phật Dạy"),
        DailyQuote("Lòng vị tha là đỉnh cao của đạo đức.", "Đức Phật"),
        DailyQuote("Hãy sống chậm rãi, nhưng vững chắc như núi.", "Lời Phật Dạy"),
        DailyQuote("Sự lắng nghe sâu sắc là một nghệ thuật.", "Thích Nhất Hạnh"),
        DailyQuote("Cuộc sống không có mục đích thì như thuyền không lái.", "Lời Phật Dạy"),
        DailyQuote("Hãy giữ tâm như đất, chịu được mọi gánh nặng.", "Kinh Pháp Cú"),
        DailyQuote("Mọi thứ đều có thời điểm của nó, đừng nôn nóng.", "Lời Phật Dạy"),
        DailyQuote("Tình yêu thương là câu trả lời cho mọi vấn đề.", "Đức Phật"),
        DailyQuote("Sống không tỉnh thức khác nào chết trên đời.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy trân quý từng ngày như ngày cuối cùng.", "Lời Phật Dạy"),
        DailyQuote("Đừng để tình yêu biến thành sự sở hữu.", "Đức Phật"),
        DailyQuote("Kiếp người khó được, Phật pháp khó nghe.", "Kinh Tạp A Hàm"),
        DailyQuote("Hãy là người mang lại hạnh phúc cho gia đình và xã hội.", "Lời Phật Dạy"),
        DailyQuote("Thiền tập giúp tâm hồn thanh lọc và an lạc.", "Thích Nhất Hạnh"),
        DailyQuote("Sự tham lam là vực thẳm không đáy của khổ đau.", "Đức Phật"),
        DailyQuote("Hãy học cách chấp nhận những gì không thể thay đổi.", "Lời Phật Dạy"),
        DailyQuote("Mỗi em bé là một đóa hoa, hãy nâng niu.", "Thích Nhất Hạnh"),
        DailyQuote("Lời nói có thể xây dựng hoặc phá hủy, hãy chọn lời nói yêu thương.", "Kinh Pháp Cú"),
        DailyQuote("Hãy sống hài hòa với thiên nhiên.", "Đức Phật"),
        DailyQuote("Đừng chạy theo danh vọng, hãy sống thật với chính mình.", "Lời Phật Dạy"),
        DailyQuote("Sự tập trung chánh niệm giúp ta đạt được mục tiêu.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy cho đi yêu thương, bạn sẽ nhận lại yêu thương.", "Lời Phật Dạy"),
        DailyQuote("Tâm từ bi làm dịu mát mọi khổ đau.", "Đức Phật"),
        DailyQuote("Sống không hối hận về những gì đã qua.", "Lời Phật Dạy"),
        DailyQuote("Đừng sợ hãi trước thay đổi, đó là cơ hội để phát triển.", "Lời Phật Dạy"),
        DailyQuote("Mỗi người là một thế giới riêng, hãy tôn trọng sự khác biệt.", "Đức Phật"),
        DailyQuote("Hãy lắng nghe bằng trái tim, không chỉ bằng tai.", "Thích Nhất Hạnh"),
        DailyQuote("Sự hào phóng mở ra cánh cửa của hạnh phúc.", "Kinh Pháp Cú"),
        DailyQuote("Cuộc đời như giấc mộng, đừng quá chấp vào thực tại.", "Kinh Kim Cang"),
        DailyQuote("Hãy sống với đức tính khiêm nhường.", "Lời Phật Dạy"),
        DailyQuote("Mọi sân hận đều do vô minh mà ra.", "Đức Phật"),
        DailyQuote("Hãy yêu thương kẻ thù của bạn, đó là cách chiến thắng cao nhất.", "Lời Phật Dạy"),
        DailyQuote("Sự bình an không đến từ bên ngoài mà từ trong tâm.", "Thích Nhất Hạnh"),
        DailyQuote("Đừng chấp vào hình tướng bên ngoài, hãy nhìn vào bản chất.", "Kinh Kim Cang"),
        DailyQuote("Hãy làm việc tốt khi có thể, vì cuộc đời ngắn ngủi.", "Lời Phật Dạy"),
        DailyQuote("Lòng biết ơn là nguồn năng lượng tích cực.", "Lời Phật Dạy"),
        DailyQuote("Mọi nỗi đau sẽ qua, nhưng bài học còn mãi.", "Đức Phật"),
        DailyQuote("Hãy sống với tâm thiện, đó là bảo vật vô giá.", "Lời Phật Dạy"),
        DailyQuote("Sự chánh niệm giúp ta không bị cuốn vào vòng xoáy khổ đau.", "Thích Nhất Hạnh"),
        DailyQuote("Đừng gieo nhân ác nếu không muốn gặt quả đắng.", "Kinh Pháp Cú"),
        DailyQuote("Hãy là người bạn đồng hành tốt trên con đường tu tập.", "Lời Phật Dạy"),
        DailyQuote("Cuộc đời là vô thường như áng mây bay.", "Kinh Kim Cang"),
        DailyQuote("Tình yêu thương là năng lượng chữa lành mọi vết thương.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy học cách buông xả để tâm hồn được nhẹ nhàng.", "Lời Phật Dạy"),
        DailyQuote("Sự kiên nhẫn là mẹ của mọi thành công.", "Đức Phật"),
        DailyQuote("Mỗi giây phút là cơ hội để bắt đầu lại.", "Lời Phật Dạy"),
        DailyQuote("Hãy nhìn cuộc đời bằng con mắt của sự hiểu biết.", "Thích Nhất Hạnh"),
        DailyQuote("Đừng để lòng ghen tị làm hỏng tâm hồn.", "Kinh Pháp Cú"),
        DailyQuote("Sống đời vị tha là sống đời cao đẹp nhất.", "Lời Phật Dạy"),
        DailyQuote("Tất cả chúng sinh đều có Phật tính.", "Kinh Đại Bát Niết Bàn"),
        DailyQuote("Hãy thả lỏng và buông bỏ, đó là cách để nhẹ nhàng.", "Thích Nhất Hạnh"),
        DailyQuote("Mọi thứ đều tương đối, đừng quá cứng nhắc.", "Lời Phật Dạy"),
        DailyQuote("Sự sẻ chia mang lại niềm vui nhân đôi.", "Lời Phật Dạy"),
        DailyQuote("Đừng làm điều ác, hãy làm điều lành, giữ tâm ý trong sạch.", "Kinh Pháp Cú"),
        DailyQuote("Hãy sống thanh bần mà vui vẻ, đừng sống giàu sang mà lo lắng.", "Lời Phật Dạy"),
        DailyQuote("Hạnh phúc là hành trình, không phải đích đến.", "Thích Nhất Hạnh"),
        DailyQuote("Mỗi người là một vì sao, hãy tỏa sáng theo cách riêng.", "Lời Phật Dạy"),
        DailyQuote("Sự tĩnh lặng là cánh cửa dẫn vào trí tuệ.", "Đức Phật"),
        DailyQuote("Hãy chăm sóc tâm hồn như chăm sóc khu vườn.", "Thích Nhất Hạnh"),
        DailyQuote("Đừng so đo thiệt hơn, hãy sống rộng lượng.", "Lời Phật Dạy"),
        DailyQuote("Niềm vui chân thật không phụ thuộc vào vật chất.", "Đức Phật"),
        DailyQuote("Hãy đi con đường của chính mình, đừng bắt chước người khác.", "Lời Phật Dạy"),
        DailyQuote("Từ bi và trí tuệ là hai cánh của con chim giác ngộ.", "Kinh Hoa Nghiêm"),
        DailyQuote("Mỗi bước chân là một lời cầu nguyện.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy nhìn vào bên trong, sự giác ngộ ở ngay đó.", "Đức Phật"),
        DailyQuote("Sống đời không đáng sợ, đáng sợ là không biết mình là ai.", "Lời Phật Dạy"),
        DailyQuote("Hãy kiểm soát tâm trí, đừng để tâm trí kiểm soát bạn.", "Kinh Pháp Cú"),
        DailyQuote("Sự chấp nhận là bước đầu tiên của sự chuyển hóa.", "Thích Nhất Hạnh"),
        DailyQuote("Đừng oán trách số phận, hãy thay đổi nhân quả.", "Lời Phật Dạy"),
        DailyQuote("Hãy sống đơn giản và từ bi với muôn loài.", "Đức Phật"),
        DailyQuote("Mỗi giọt nước mắt đều chứa đựng một bài học.", "Lời Phật Dạy"),
        DailyQuote("Thiên đường hay địa ngục đều ở trong tâm ta.", "Kinh Hoa Nghiêm"),
        DailyQuote("Hãy thương yêu và kính trọng cha mẹ của mình.", "Lời Phật Dạy"),
        DailyQuote("Không có tình yêu nào lớn hơn tình yêu thương muôn loài.", "Đức Phật"),
        DailyQuote("Hãy sống khiêm nhường như dòng nước thấp.", "Lời Phật Dạy"),
        DailyQuote("Sự siêng năng chánh niệm mang lại hoa trái ngọt ngào.", "Thích Nhất Hạnh"),
        DailyQuote("Đừng để bản ngã che lấp ánh sáng trí tuệ.", "Kinh Pháp Cú"),
        DailyQuote("Hãy cho đi mà không mong cầu, đó là hạnh phúc tối thượng.", "Đức Phật"),
        DailyQuote("Cuộc sống ngắn ngủi, hãy sống thật ý nghĩa.", "Lời Phật Dạy"),
        DailyQuote("Mỗi ngày là một cơ hội để học hỏi và trưởng thành.", "Lời Phật Dạy"),
        DailyQuote("Tâm hồn thanh tịnh là nơi trú ẩn bình yên nhất.", "Đức Phật"),
        DailyQuote("Hãy đối xử tốt với người khác như muốn được đối xử tốt.", "Lời Phật Dạy"),
        DailyQuote("Sự thật luôn chiến thắng, dù có bị che giấu.", "Lời Phật Dạy"),
        DailyQuote("Đừng chạy theo dục vọng, hãy sống tiết chế.", "Kinh Pháp Cú"),
        DailyQuote("Hạnh phúc không phải là đích đến mà là cách ta đi.", "Thích Nhất Hạnh"),
        DailyQuote("Mọi oán hận đều do chấp ngã mà ra.", "Đức Phật"),
        DailyQuote("Hãy sống chan hòa với tất cả chúng sinh.", "Lời Phật Dạy"),
        DailyQuote("Lời nói ngọt ngào làm đẹp lòng người.", "Kinh Pháp Cú"),
        DailyQuote("Sự lười biếng là kẻ thù của thành công.", "Lời Phật Dạy"),
        DailyQuote("Hãy biết ơn người đã chỉ ra lỗi lầm của bạn.", "Đức Phật"),
        DailyQuote("Mỗi niệm lành là một viên ngọc quý.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy sống với chánh niệm trong từng hành động.", "Lời Phật Dạy"),
        DailyQuote("Sự buông bỏ không phải là mất mát, mà là giải thoát.", "Đức Phật"),
        DailyQuote("Đừng để thành kiến che mờ lý trí.", "Lời Phật Dạy"),
        DailyQuote("Hãy tự mình thắp đuốc lên mà đi.", "Kinh Đại Bát Niết Bàn"),
        DailyQuote("Tình thương chân thật không phân biệt giàu nghèo.", "Đức Phật"),
        DailyQuote("Sống có ích cho đời là sống đẹp nhất.", "Lời Phật Dạy"),
        DailyQuote("Mọi sự đều do duyên, đừng cố gắng ép duyên.", "Lời Phật Dạy"),
        DailyQuote("Thiên đường là đây, hạnh phúc là đây, ngay trong giây phút hiện tại.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy tu tập tâm từ bi với tất cả chúng sinh.", "Đức Phật"),
        DailyQuote("Sự giận dữ là một dạng của sự yếu đuối.", "Lời Phật Dạy"),
        DailyQuote("Đừng làm khổ mình, đừng làm khổ người.", "Kinh Pháp Cú"),
        DailyQuote("Hãy sống vị tha và bao dung.", "Lời Phật Dạy"),
        DailyQuote("Mỗi bài toán đều có lời giải, hãy kiên nhẫn tìm ra.", "Đức Phật"),
        DailyQuote("Sự chân thật soi sáng con đường tâm linh.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy dùng tình thương để đáp lại hận thù.", "Kinh Pháp Cú"),
        DailyQuote("Mọi việc đều có nhân quả của nó.", "Đức Phật"),
        DailyQuote("Hãy sống đúng với lương tâm và đạo đức.", "Lời Phật Dạy"),
        DailyQuote("Sự tự do đích thực là tự do khỏi tham sân si.", "Đức Phật"),
        DailyQuote("Hãy chăm sóc sức khỏe thể chất và tinh thần.", "Lời Phật Dạy"),
        DailyQuote("Không có gì thường hằng, mọi thứ đều đổi thay.", "Kinh Vô Thường"),
        DailyQuote("Hãy yêu thương như mặt trời chiếu sáng muôn loài.", "Lời Phật Dạy"),
        DailyQuote("Mỗi chúng sinh đều bình đẳng trong tình thương của Phật.", "Đức Phật"),
        DailyQuote("Cuộc đời là một cuốn sách, hãy đọc nó bằng trái tim.", "Thích Nhất Hạnh"),
        DailyQuote("Đừng mải mê chạy theo thế gian, hãy quay về nương tựa chính mình.", "Lời Phật Dạy"),
        DailyQuote("Sự khổ đau là liều thuốc đắng cho tâm hồn.", "Đức Phật"),
        DailyQuote("Hãy tinh tấn tu học, đừng buông lung.", "Kinh Pháp Cú"),
        DailyQuote("Đời người như giọt sương mai, hãy sống trọn vẹn từng khoảnh khắc.", "Lời Phật Dạy"),
        DailyQuote("Lòng từ bi là suối nguồn tươi mát cho thế gian.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy sống chan hòa với thiên nhiên và vạn vật.", "Đức Phật"),
        DailyQuote("Nhân nào quả nấy, hãy gieo nhân lành.", "Kinh Nhân Quả"),
        DailyQuote("Hãy tập trung vào hiện tại, đó là món quà của cuộc sống.", "Lời Phật Dạy"),
        DailyQuote("Sự cô đơn không đến từ sự cô độc mà từ tâm hồn khép kín.", "Thích Nhất Hạnh"),
        DailyQuote("Đừng để sợ hãi chi phối cuộc đời bạn.", "Đức Phật"),
        DailyQuote("Mỗi người đều có khả năng giác ngộ như nhau.", "Kinh Pháp Hoa"),
        DailyQuote("Hãy sống một cuộc đời không hối tiếc.", "Lời Phật Dạy"),
        DailyQuote("Tâm hồn rộng mở đón nhận yêu thương muôn loài.", "Thích Nhất Hạnh"),
        DailyQuote("Sự chia rẽ là nguồn gốc của mọi xung đột.", "Đức Phật"),
        DailyQuote("Hãy cẩn trọng với từng lời nói, vì nó có thể xây hay phá.", "Kinh Pháp Cú"),
        DailyQuote("Mọi thứ rồi sẽ qua, chỉ có tình thương ở lại.", "Lời Phật Dạy"),
        DailyQuote("Cuộc sống là một phép lạ, hãy mở mắt đón nhận.", "Thích Nhất Hạnh"),
        DailyQuote("Đừng đánh mất mình trong những lo toan thường nhật.", "Lời Phật Dạy"),
        DailyQuote("Hãy trân trọng mối quan hệ với người thân yêu.", "Lời Phật Dạy"),
        DailyQuote("Sự hỷ xả mang lại an lạc cho tâm hồn.", "Đức Phật"),
        DailyQuote("Hãy biết dừng lại đúng lúc.", "Thích Nhất Hạnh"),
        DailyQuote("Đời là bể khổ, hãy tìm đường giải thoát.", "Lời Phật Dạy"),
        DailyQuote("Mỗi việc thiện dù nhỏ cũng có giá trị vô cùng.", "Kinh Pháp Cú"),
        DailyQuote("Hãy sống chánh niệm ngay cả khi ăn, đi, đứng, nằm.", "Thích Nhất Hạnh"),
        DailyQuote("Sự buông bỏ là chìa khóa của tự do.", "Đức Phật"),
        DailyQuote("Hãy yêu thương và bảo vệ môi trường sống.", "Lời Phật Dạy"),
        DailyQuote("Đừng sống ích kỷ, hãy nghĩ đến người khác.", "Lời Phật Dạy"),
        DailyQuote("Tâm từ bi mở ra cánh cửa của hạnh phúc.", "Thích Nhất Hạnh"),
        DailyQuote("Mọi sự đều có thể thay đổi nếu ta có đủ niềm tin.", "Đức Phật"),
        DailyQuote("Hãy làm việc tốt mỗi ngày để trái tim được thanh thản.", "Lời Phật Dạy"),
        DailyQuote("Sự thiền định là phương thuốc nhiệm màu cho tâm trí.", "Thích Nhất Hạnh"),
        DailyQuote("Đời người quý ở chỗ biết đủ, biết dừng.", "Lời Phật Dạy"),
        DailyQuote("Hãy sống với tâm nguyện giúp đời, giúp người.", "Đức Phật"),
        DailyQuote("Kiếp người khó được, hãy sống thật ý nghĩa.", "Kinh Tạp A Hàm"),
        DailyQuote("Mỗi ngày hãy dành thời gian để nhìn lại mình.", "Lời Phật Dạy"),
        DailyQuote("Sự thật là ngọn đèn soi sáng con đường tâm linh.", "Đức Phật"),
        DailyQuote("Hãy là một người con hiếu thảo, một người bạn tốt.", "Lời Phật Dạy"),
        DailyQuote("Tâm không vọng động thì tự nhiên an lạc.", "Kinh Hoa Nghiêm"),
        DailyQuote("Sống ở đời đừng quá cầu toàn, hãy chấp nhận khuyết điểm.", "Lời Phật Dạy"),
        DailyQuote("Hãy cho đi yêu thương mà không mong đền đáp.", "Đức Phật"),
        DailyQuote("Sự sợ hãi chỉ tồn tại khi ta thiếu hiểu biết.", "Thích Nhất Hạnh"),
        DailyQuote("Mỗi lần vấp ngã là một lần học hỏi.", "Lời Phật Dạy"),
        DailyQuote("Hãy giữ tâm thanh tịnh giữa dòng đời vạn biến.", "Lời Phật Dạy"),
        DailyQuote("Tình yêu thương là món quà vô giá của cuộc sống.", "Đức Phật"),
        DailyQuote("Đừng để quá khứ ràng buộc, hãy bước tiếp.", "Thích Nhất Hạnh"),
        DailyQuote("Sống đẹp là sống có ích cho đời.", "Lời Phật Dạy"),
        DailyQuote("Hãy cầu nguyện cho tất cả chúng sinh được an lạc.", "Kinh Từ Bi"),
        DailyQuote("Mỗi việc làm tốt là một đóa hoa trong vườn tâm.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy sống chân thật với chính mình.", "Lời Phật Dạy"),
        DailyQuote("Sự bình an trong tâm là nền tảng của hạnh phúc.", "Đức Phật"),
        DailyQuote("Mọi thù hận đều tan biến trước tình yêu thương.", "Kinh Pháp Cú"),
        DailyQuote("Hãy sống một đời đơn giản và thanh bần.", "Lời Phật Dạy"),
        DailyQuote("Tâm hồn trong sạch là tấm gương phản chiếu Phật tánh.", "Kinh Đại Bát Niết Bàn"),
        DailyQuote("Đừng để sân hận làm mờ tâm trí.", "Lời Phật Dạy"),
        DailyQuote("Mỗi ngày hãy thực hành lòng biết ơn và từ bi.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy học cách lắng nghe tiếng nói của tâm hồn.", "Đức Phật"),
        DailyQuote("Sự cống hiến cho cộng đồng là điều cao quý.", "Lời Phật Dạy"),
        DailyQuote("Mọi khó khăn đều là cơ hội để rèn luyện bản thân.", "Lời Phật Dạy"),
        DailyQuote("Hãy buông bỏ những gánh nặng không cần thiết.", "Thích Nhất Hạnh"),
        DailyQuote("Tình yêu thương là nguồn năng lượng vô tận.", "Đức Phật"),
        DailyQuote("Sống với chánh niệm là sống với tình yêu thương.", "Thích Nhất Hạnh"),
        DailyQuote("Đừng tham lam của cải, hãy tham lam học hỏi.", "Lời Phật Dạy"),
        DailyQuote("Hãy là nơi nương tựa cho người khốn khó.", "Lời Phật Dạy"),
        DailyQuote("Mỗi ngày mới là một khởi đầu mới.", "Đức Phật"),
        DailyQuote("Sự cầu toàn là nguồn gốc của thất vọng.", "Lời Phật Dạy"),
        DailyQuote("Hãy nhìn đời bằng con mắt thương yêu.", "Thích Nhất Hạnh"),
        DailyQuote("Cuộc sống là vô thường, đừng chấp vào bất cứ điều gì.", "Kinh Kim Cang"),
        DailyQuote("Hãy sống vui, sống khỏe, sống có ích.", "Lời Phật Dạy"),
        DailyQuote("Tâm hồn cao thượng là tâm hồn biết tha thứ.", "Đức Phật"),
        DailyQuote("Mỗi em bé đều là một vị Phật tương lai.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy tinh tấn và kiên trì trên con đường tu tập.", "Lời Phật Dạy"),
        DailyQuote("Sự hiểu biết chân chính đến từ sự trải nghiệm.", "Đức Phật"),
        DailyQuote("Hãy sống hết mình cho hiện tại.", "Thích Nhất Hạnh"),
        DailyQuote("Đừng để tâm bị xao động bởi khen chê.", "Lời Phật Dạy"),
        DailyQuote("Tình thương mở ra cánh cửa tâm hồn.", "Đức Phật"),
        DailyQuote("Hãy sống trọn vẹn với những gì mình có.", "Lời Phật Dạy"),
        DailyQuote("Mỗi người là một mắt xích của cuộc đời.", "Thích Nhất Hạnh"),
        DailyQuote("Sự thực tập chánh niệm mang lại an lạc ngay trong hiện tại.", "Thích Nhất Hạnh"),
        DailyQuote("Hãy đón nhận mọi thử thách bằng trái tim dũng cảm.", "Lời Phật Dạy"),
        DailyQuote("Đời sống là một tác phẩm nghệ thuật.", "Thích Nhất Hạnh")
    )

    fun getDailyQuote(): DailyQuote {
        val calendar = Calendar.getInstance()
        val dayOfYear = calendar.get(Calendar.DAY_OF_YEAR)
        return BUDDHIST_QUOTES[dayOfYear % BUDDHIST_QUOTES.size]
    }

    fun getRandomQuote(): DailyQuote {
        return BUDDHIST_QUOTES.random()
    }
}
